name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump_type:
        description: Version bump type
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Fetch all tags
      run: git fetch --tags --force

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Determine version bump type
      id: bump_type
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "type=${{ github.event.inputs.bump_type }}" >> $GITHUB_OUTPUT
        else
          # Auto-detect from commit messages (feat: = minor, fix: = patch, breaking: = major)
          echo "type=auto" >> $GITHUB_OUTPUT
        fi

    - name: Bump version and update changelog
      run: |
        BUMP_TYPE="${{ steps.bump_type.outputs.type }}"
        if [ "$BUMP_TYPE" = "auto" ]; then
          uv run cz bump --yes
        else
          uv run cz bump --increment $BUMP_TYPE --yes
        fi
        echo "NEW_VERSION=$(uv run cz version --project)" >> $GITHUB_ENV

    - name: Push changes
      run: |
        git push
        git push --tags

    - name: Build package
      run: uv build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body_path: CHANGELOG.md
        files: |
          dist/*
        draft: false
        prerelease: false
