name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: Version bump type
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@7910d36f4f8f88194c023eb2d07e7c72c8970cd8 # v4.1.1

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version and update changelog
      run: |
        uv run cz bump --increment ${{ github.event.inputs.bump_type }} --yes
        echo "NEW_VERSION=$(uv run cz version --project)" >> $GITHUB_ENV

    - name: Push changes
      run: |
        git push
        git push --tags

    - name: Build package
      run: uv build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@e7a8f85e1c67a31e6ac94f9150f4d88c3f5c367a # v2.2.0
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body_path: CHANGELOG.md
        files: |
          dist/*
        draft: false
        prerelease: false

    - name: Publish to PyPI
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv run pip install twine
        uv run twine upload dist/*
