name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Bump version and create release
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_TOKEN }}

    - name: Create bump and changelog
      id: cz
      uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # master
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        changelog_increment_filename: body.md

    - name: Print Version
      run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0

    - name: Set up Python
      run: uv python install 3.12

    - name: Build package
      run: uv build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
      with:
        body_path: body.md
        tag_name: ${{ steps.cz.outputs.version }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
